name: metaverse_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_native_splash: 2.2.4
  get_storage: 2.0.3
  persistent_bottom_nav_bar: 4.0.2
  font_awesome_flutter: 10.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

